project:
  type: website
  output-dir: _site
  
website:
  title: "Git Submodules Learning Repository"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: content/01_git_submodules/index.qmd
        text: Git Submodules
      - href: content/02_cursor_specific_files/index.qmd
        text: Cursor Files
  sidebar:
    style: "docked"
    contents:
      - section: "Git Submodules"
        contents:
          - content/01_git_submodules/index.qmd
          - content/01_git_submodules/creating_submodules.qmd
          - content/01_git_submodules/managing_submodules.qmd
      - section: "Cursor-Specific Files"
        contents:
          - content/02_cursor_specific_files/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 